apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver
spec:
  selector:
    matchLabels:
      app: driver
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
        - name: driver
          image: img-deployment
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  selector:
    app: driver
  ports:
    - port: 8081
      targetPort: 8081

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: driver-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
