apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver
spec:
  selector:
    matchLabels:
      app: driver
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
        - name: driver
          image: img-deployment
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: driver
