basePath: /
definitions:
  main.Driver:
    properties:
      name:
        example: Sidarta S
        type: string
      uuid:
        example: 127a2285-0fd8-4df9-b4eb-485292f3e345
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: Driver API
  license:
    name: Full Cycle License
    url: http://www.fullcycle.com.br
  termsOfService: http://swagger.io/terms/
  title: Maratona Full Cycle Driver API
  version: "1.0"
paths:
  /drivers:
    get:
      consumes:
      - application/json
      description: Get all drivers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Driver'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: List drivers
      tags:
      - drivers
  /drivers/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: driver ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Driver'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get a driver
      tags:
      - drivers
swagger: "2.0"
